services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ald_laravel

    working_dir: /var/www/html

    volumes:
      - .:/var/www/html

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy

    networks:
      - ald_network


  db:
    image: postgres:16-alpine

    container_name: ald_postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: ald_motorshop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

    ports:
      - "5432:5432"

    volumes:
      - ald_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U admin -d ald_motorshop"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - ald_network


  node:
    image: node:22-alpine

    container_name: ald_node

    working_dir: /var/www/html

    volumes:
      - .:/var/www/html

    ports:
      - "5173:5173"

    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

    networks:
      - ald_network


networks:
  ald_network:


volumes:
  ald_postgres_data: