<?php

namespace App\Http\Controllers\Staff;

use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;

class StaffPaymentsController extends Controller
{
    public function data(): JsonResponse
    {
        return response()->json([
            'summary' => [
                'total' => 36,
                'unpaid' => 6,
                'waiting_for_verification' => 3,
                'paid' => 18,
            ],
            'payments' => [
                [
                    'order_reference' => 'ALD-2026-000127',
                    'customer' => 'Angela Cruz',
                    'total' => '₱3,400.00',
                    'table_total' => '₱3,400',
                    'method' => 'Online Payment',
                    'amount_paid' => '₱3,400.00',
                    'table_amount_paid' => '₱3,400',
                    'status' => 'Waiting for Verification',
                    'payment_date' => 'Aug 7, 2026',
                    'date_value' => '2026-08-07',
                    'payment_date_full' => 'August 7, 2026 - 4:32 PM',
                    'payment_reference' => 'PAY-873421',
                    'verified_by' => 'Not yet verified',
                    'verification_date' => '—',
                    'action' => 'Review Payment',
                ],
                [
                    'order_reference' => 'ALD-2026-000124',
                    'customer' => 'Carla Mendoza',
                    'total' => '₱2,470.00',
                    'table_total' => '₱2,470',
                    'method' => 'Online Payment',
                    'amount_paid' => '₱2,470.00',
                    'table_amount_paid' => '₱2,470',
                    'status' => 'Paid',
                    'payment_date' => 'Aug 7, 2026',
                    'date_value' => '2026-08-07',
                    'payment_date_full' => 'August 7, 2026 - 2:18 PM',
                    'payment_reference' => 'PAY-873108',
                    'verified_by' => 'Staff User',
                    'verification_date' => 'August 7, 2026 - 2:25 PM',
                    'action' => 'View Payment',
                ],
                [
                    'order_reference' => 'ALD-2026-000126',
                    'customer' => 'John Doe',
                    'total' => '₱3,260.00',
                    'table_total' => '₱3,260',
                    'method' => 'Cash / Pay at Branch',
                    'amount_paid' => '—',
                    'table_amount_paid' => '—',
                    'status' => 'Unpaid',
                    'payment_date' => '—',
                    'date_value' => '',
                    'payment_date_full' => '—',
                    'payment_reference' => '—',
                    'verified_by' => 'Not yet verified',
                    'verification_date' => '—',
                    'action' => 'View Payment',
                ],
                [
                    'order_reference' => 'ALD-2026-000125',
                    'customer' => 'Paolo Santos',
                    'total' => '₱920.00',
                    'table_total' => '₱920',
                    'method' => 'Cash / Pay at Branch',
                    'amount_paid' => '—',
                    'table_amount_paid' => '—',
                    'status' => 'Waiting for Payment',
                    'payment_date' => '—',
                    'date_value' => '',
                    'payment_date_full' => '—',
                    'payment_reference' => '—',
                    'verified_by' => 'Not yet verified',
                    'verification_date' => '—',
                    'action' => 'View Payment',
                ],
                [
                    'order_reference' => 'ALD-2026-000123',
                    'customer' => 'Miguel Ramos',
                    'total' => '₱1,680.00',
                    'table_total' => '₱1,680',
                    'method' => 'Online Payment',
                    'amount_paid' => '₱1,680.00',
                    'table_amount_paid' => '₱1,680',
                    'status' => 'Paid',
                    'payment_date' => 'Aug 6, 2026',
                    'date_value' => '2026-08-06',
                    'payment_date_full' => 'August 6, 2026 - 5:40 PM',
                    'payment_reference' => 'PAY-872944',
                    'verified_by' => 'Staff User',
                    'verification_date' => 'August 6, 2026 - 5:46 PM',
                    'action' => 'View Payment',
                ],
                [
                    'order_reference' => 'ALD-2026-000120',
                    'customer' => 'Grace Lopez',
                    'total' => '₱1,250.00',
                    'table_total' => '₱1,250',
                    'method' => 'Online Payment',
                    'amount_paid' => '₱1,250.00',
                    'table_amount_paid' => '₱1,250',
                    'status' => 'Failed',
                    'payment_date' => 'Aug 6, 2026',
                    'date_value' => '2026-08-06',
                    'payment_date_full' => 'August 6, 2026 - 11:15 AM',
                    'payment_reference' => 'PAY-872601',
                    'verified_by' => 'Not yet verified',
                    'verification_date' => '—',
                    'action' => 'Review Payment',
                ],
                [
                    'order_reference' => 'ALD-2026-000117',
                    'customer' => 'Daniel Reyes',
                    'total' => '₱2,800.00',
                    'table_total' => '₱2,800',
                    'method' => 'Online Payment',
                    'amount_paid' => '₱2,800.00',
                    'table_amount_paid' => '₱2,800',
                    'status' => 'Refunded',
                    'payment_date' => 'Aug 5, 2026',
                    'date_value' => '2026-08-05',
                    'payment_date_full' => 'August 5, 2026 - 3:05 PM',
                    'payment_reference' => 'PAY-872288',
                    'verified_by' => 'Staff User',
                    'verification_date' => 'August 5, 2026 - 3:12 PM',
                    'action' => 'View Payment',
                ],
                [
                    'order_reference' => 'ALD-2026-000115',
                    'customer' => 'Maria Santos',
                    'total' => '₱750.00',
                    'table_total' => '₱750',
                    'method' => 'Cash / Pay at Branch',
                    'amount_paid' => '—',
                    'table_amount_paid' => '—',
                    'status' => 'Cancelled',
                    'payment_date' => '—',
                    'date_value' => '',
                    'payment_date_full' => '—',
                    'payment_reference' => '—',
                    'verified_by' => 'Not yet verified',
                    'verification_date' => '—',
                    'action' => 'View Payment',
                ],
            ],
        ]);
    }
}
