<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use RuntimeException;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $officialCategories = [
            'Engine Parts',
            'Brake Parts',
            'Electrical Parts',
            'Suspension Parts',
            'Transmission Parts',
            'Body & Exterior',
            'Tires & Wheels',
            'Accessories & Maintenance',
        ];

        $categoryIds = Category::query()
            ->whereIn('name', $officialCategories)
            ->pluck('id', 'name');

        foreach ($officialCategories as $categoryName) {
            if (! isset($categoryIds[$categoryName])) {
                throw new RuntimeException(
                    "Missing official category: {$categoryName}"
                );
            }
        }

        $products = [
            [
                'category_id' => $categoryIds['Electrical Parts'],
                'name' => 'Honda Genuine Spark Plug',
                'part_number' => 'HON-001',
                'brand' => 'Honda',
                'description' => 'Honda motorcycle spark plug.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787560931/Honda-Spark-Plug.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Accessories & Maintenance'],
                'name' => 'Honda Air Filter',
                'part_number' => 'HON-002',
                'brand' => 'Honda',
                'description' => 'Honda motorcycle air filter.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561452/Honda-Air-Filter.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Brake Parts'],
                'name' => 'Honda Front Brake Pad Set',
                'part_number' => 'HON-003',
                'brand' => 'Honda',
                'description' => 'Honda motorcycle front brake pad set.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561477/Honda-Brake-Pad.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Accessories & Maintenance'],
                'name' => 'Honda Oil Filter',
                'part_number' => 'HON-004',
                'brand' => 'Honda',
                'description' => 'Honda motorcycle oil filter.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561449/Honda-Oil-Filter.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Transmission Parts'],
                'name' => 'Honda Drive Chain Kit',
                'part_number' => 'HON-005',
                'brand' => 'Honda',
                'description' => 'Honda motorcycle drive chain kit.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561477/Honda-Chain-Kit.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Transmission Parts'],
                'name' => 'Honda Drive Belt',
                'part_number' => 'HON-006',
                'brand' => 'Honda',
                'description' => 'Honda motorcycle drive belt.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787560941/Honda-Drive-Belt.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Electrical Parts'],
                'name' => 'Honda Motorcycle Battery',
                'part_number' => 'HON-007',
                'brand' => 'Honda',
                'description' => 'Honda motorcycle battery.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561463/Honda-Battery.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Tires & Wheels'],
                'name' => 'Honda Front Tire',
                'part_number' => 'HON-008',
                'brand' => 'Honda',
                'description' => 'Honda motorcycle front tire.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787560944/Honda-Front-Tire.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Transmission Parts'],
                'name' => 'Honda Clutch Weight Set',
                'part_number' => 'HON-009',
                'brand' => 'Honda',
                'description' => 'Honda motorcycle clutch weight set.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787560934/Honda-Clutch-Weight.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Suspension Parts'],
                'name' => 'Honda Shock Absorber',
                'part_number' => 'HON-010',
                'brand' => 'Honda',
                'description' => 'Honda motorcycle shock absorber.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787560947/Honda-Shock-Absorber.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Engine Parts'],
                'name' => 'Honda Filter Set',
                'part_number' => 'HON-011',
                'brand' => 'Honda',
                'description' => 'Honda motorcycle filter set.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561337/Honda-Filter-Set.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Body & Exterior'],
                'name' => 'Honda Front Cover Pipe (Chrome)',
                'part_number' => 'HON-012',
                'brand' => 'Honda',
                'description' => 'Honda motorcycle front cover pipe.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561351/Honda-Front-Cover-Pipe.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Accessories & Maintenance'],
                'name' => 'Suzuki Genuine Oil Filter',
                'part_number' => 'SUZ-001',
                'brand' => 'Suzuki',
                'description' => 'Suzuki motorcycle oil filter.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561055/Suzuki-Oil-Filter.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Electrical Parts'],
                'name' => 'Suzuki Genuine Spark Plug',
                'part_number' => 'SUZ-002',
                'brand' => 'Suzuki',
                'description' => 'Suzuki motorcycle spark plug.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561055/Suzuki-Spark-Plug.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Accessories & Maintenance'],
                'name' => 'Suzuki Air Filter / Air Cleaner',
                'part_number' => 'SUZ-003',
                'brand' => 'Suzuki',
                'description' => 'Suzuki motorcycle air filter and air cleaner.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561036/Suzuki-Air-Filter.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Brake Parts'],
                'name' => 'Suzuki Brake Pad',
                'part_number' => 'SUZ-004',
                'brand' => 'Suzuki',
                'description' => 'Suzuki motorcycle brake pad.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561053/Suzuki-Brake-Pad.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Brake Parts'],
                'name' => 'Suzuki Brake Shoe',
                'part_number' => 'SUZ-005',
                'brand' => 'Suzuki',
                'description' => 'Suzuki motorcycle brake shoe.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561079/Suzuki-Brake-Shoe.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Transmission Parts'],
                'name' => 'Suzuki Drive Chain Kit',
                'part_number' => 'SUZ-006',
                'brand' => 'Suzuki',
                'description' => 'Suzuki motorcycle drive chain kit.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561052/Suzuki-Chain-Kit.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Transmission Parts'],
                'name' => 'Suzuki Sprocket',
                'part_number' => 'SUZ-007',
                'brand' => 'Suzuki',
                'description' => 'Suzuki motorcycle sprocket.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561050/Suzuki-Sprocket.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Electrical Parts'],
                'name' => 'Suzuki Battery',
                'part_number' => 'SUZ-008',
                'brand' => 'Suzuki',
                'description' => 'Suzuki motorcycle battery.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561037/Suzuki-Battery.webp',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Tires & Wheels'],
                'name' => 'Suzuki Tire',
                'part_number' => 'SUZ-009',
                'brand' => 'Suzuki',
                'description' => 'Suzuki motorcycle tire.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561038/Suzuki-Tire.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Accessories & Maintenance'],
                'name' => 'ECSTAR Genuine Engine Oil',
                'part_number' => 'SUZ-010',
                'brand' => 'Suzuki',
                'description' => 'ECSTAR genuine motorcycle engine oil.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561038/ECSTAR-Engine-Oil.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Transmission Parts'],
                'name' => 'Yamaha V-Belt',
                'part_number' => 'YAM-001',
                'brand' => 'Yamaha',
                'description' => 'Yamaha motorcycle V-belt.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561168/Yamaha-V-Belt.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Brake Parts'],
                'name' => 'Yamaha Brake Pad Kit',
                'part_number' => 'YAM-002',
                'brand' => 'Yamaha',
                'description' => 'Yamaha motorcycle brake pad kit.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561155/Yamaha-Brake-Pad.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Accessories & Maintenance'],
                'name' => 'Yamaha Air Cleaner Element Assy',
                'part_number' => 'YAM-003',
                'brand' => 'Yamaha',
                'description' => 'Yamaha motorcycle air cleaner element assembly.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561170/Yamaha-Air-Filter.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Accessories & Maintenance'],
                'name' => 'Yamaha Element Assy, Oil Cleaner',
                'part_number' => 'YAM-004',
                'brand' => 'Yamaha',
                'description' => 'Yamaha motorcycle oil cleaner element assembly.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561179/Yamaha-Oil-Filter.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Electrical Parts'],
                'name' => 'Yamaha Spark Plug',
                'part_number' => 'YAM-005',
                'brand' => 'Yamaha',
                'description' => 'Yamaha motorcycle spark plug.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561151/Yamaha-Spark-Plug.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Transmission Parts'],
                'name' => 'Yamaha Chain',
                'part_number' => 'YAM-006',
                'brand' => 'Yamaha',
                'description' => 'Yamaha motorcycle chain.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561161/Yamaha-Chain.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Transmission Parts'],
                'name' => 'Yamaha Sprocket',
                'part_number' => 'YAM-007',
                'brand' => 'Yamaha',
                'description' => 'Yamaha motorcycle sprocket.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561191/Yamaha-Sprocket.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Brake Parts'],
                'name' => 'Yamaha Brake Shoe Set',
                'part_number' => 'YAM-008',
                'brand' => 'Yamaha',
                'description' => 'Yamaha motorcycle brake shoe set.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561143/Yamaha-Brake-Shoe.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Accessories & Maintenance'],
                'name' => 'Yamalube Engine Oil',
                'part_number' => 'YAM-009',
                'brand' => 'Yamaha',
                'description' => 'Yamalube motorcycle engine oil.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561135/Yamalube-Engine-Oil.webp',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Accessories & Maintenance'],
                'name' => 'Yamalube Super Chain Lube',
                'part_number' => 'YAM-010',
                'brand' => 'Yamaha',
                'description' => 'Yamalube motorcycle chain lubricant.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561179/Yamalube-Chain-Lube.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Body & Exterior'],
                'name' => 'Yamaha Rear Carrier Black',
                'part_number' => 'YAM-011',
                'brand' => 'Yamaha',
                'description' => 'Yamaha motorcycle rear carrier.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561566/Yamaha-Rear-Carrier.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Electrical Parts'],
                'name' => 'Yamaha USB Charger',
                'part_number' => 'YAM-012',
                'brand' => 'Yamaha',
                'description' => 'Yamaha motorcycle USB charger.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561542/Yamaha-USB-Charger.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Suspension Parts'],
                'name' => 'Yamaha Reservoir Cap',
                'part_number' => 'YAM-013',
                'brand' => 'Yamaha',
                'description' => 'Yamaha motorcycle reservoir cap.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561579/Yamaha-Reservoir-Cap.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Transmission Parts'],
                'name' => 'Yamaha Clutch Lever',
                'part_number' => 'YAM-014',
                'brand' => 'Yamaha',
                'description' => 'Yamaha motorcycle clutch lever.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561581/Yamaha-Clutch-Lever.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Tires & Wheels'],
                'name' => 'Yamaha Wheel Rim',
                'part_number' => 'YAM-015',
                'brand' => 'Yamaha',
                'description' => 'Yamaha motorcycle wheel rim.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561559/Yamaha-Wheel-Rim.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Accessories & Maintenance'],
                'name' => 'Yamalube PEA Carbon Cleaner',
                'part_number' => 'YAM-016',
                'brand' => 'Yamaha',
                'description' => 'Yamalube motorcycle carbon cleaner.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561544/Yamalube-Carbon-Cleaner.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
            [
                'category_id' => $categoryIds['Brake Parts'],
                'name' => 'Yamaha Brake Lever',
                'part_number' => 'YAM-017',
                'brand' => 'Yamaha',
                'description' => 'Yamaha motorcycle brake lever.',
                'price' => 0.00,
                'img_url' => 'https://res.cloudinary.com/ykkjo51n/image/upload/v1787561562/Yamaha-Brake-Lever.png',
                'availability_status' => 'active',
                'status' => 'active',
            ],
        ];

        $partNumbers = array_column($products, 'part_number');

        if (count($products) !== 39 || count($partNumbers) !== count(array_unique($partNumbers))) {
            throw new RuntimeException(
                'ProductSeeder must contain exactly 39 unique products.'
            );
        }

        Product::query()
            ->whereIn('part_number', [
                'ENG-001',
                'ENG-002',
                'BRK-001',
            ])
            ->delete();

        foreach ($products as $product) {
            Product::updateOrCreate(
                [
                    'part_number' => $product['part_number'],
                ],
                $product
            );
        }
    }
}
