const pickupStyles = { Preparing: ['bg-blue-50','text-blue-700'], 'Ready for Pickup': ['bg-emerald-50','text-emerald-700'], Completed: ['bg-emerald-50','text-emerald-700'], Cancelled: ['bg-slate-100','text-slate-600'] };
const pickupTabStatus = { all:null, preparing:'Preparing', ready:'Ready for Pickup', completed:'Completed', cancelled:'Cancelled' };
const pickupElement = (tag, classes = '', text = '') => { const el = document.createElement(tag); el.className = classes; el.textContent = text; return el; };

const initializeAdminPickups = () => {
    const page = document.querySelector('[data-admin-pickups]');
    if (!page) return;
    const q = (key) => page.querySelector(`[data-admin-pickups-${key}]`);
    const endpoint = page.dataset.adminPickupsEndpoint;
    const loading=q('loading'), content=q('content'), empty=q('empty'), error=q('error'), retry=q('retry'), body=q('body'), search=q('search'), branch=q('branch'), status=q('status'), staff=q('staff'), date=q('date'), sort=q('sort'), clear=q('clear'), total=q('total'), showing=q('showing'), totalLabel=q('total-label'), active=q('active'), branches=q('branches'), branchesLoading=q('branches-loading'), branchesContent=q('branches-content'), summaryLoading=q('summary-loading'), summaryContent=q('summary-content');
    if (!endpoint || !loading || !content || !empty || !error || !retry || !body || !search || !branch || !status || !staff || !date || !sort || !clear || !total || !showing || !totalLabel || !active || !branches || !branchesLoading || !branchesContent || !summaryLoading || !summaryContent) return;
    const tabs = [...page.querySelectorAll('[data-admin-pickups-tab]')];
    let data = [], branchData = [], summary = {}, activeTab = 'all';
    const state = (name) => { const busy=name==='loading'; page.setAttribute('aria-busy',String(busy)); loading.classList.toggle('hidden',!busy); content.classList.toggle('hidden',name!=='content'); empty.classList.toggle('hidden',name!=='empty'); error.classList.toggle('hidden',name!=='error'); retry.disabled=busy; };
    const updateTabs = () => tabs.forEach((tab) => { const on=tab.dataset.adminPickupsTab===activeTab; tab.classList.toggle('border-orange-500',on);tab.classList.toggle('text-[#0B1930]',on);tab.classList.toggle('border-transparent',!on);tab.classList.toggle('text-slate-500',!on); });
    const row = (item) => { const tr=pickupElement('tr','transition hover:bg-slate-50/80'); const cells=[item.order,item.customer,`${item.branch} Branch`,item.schedule,item.amount,item.payment,'', '', ''].map((value,index)=>pickupElement('td', index===0?'whitespace-nowrap px-5 py-3.5 text-sm font-semibold text-[#0B1930]':'whitespace-nowrap px-5 py-3.5 text-sm text-slate-600',value)); const staffCell=cells[6]; if(item.staff==='—') staffCell.textContent='—'; else { const icon=pickupElement('i','fa-regular fa-user text-xs text-slate-400'); icon.setAttribute('aria-hidden','true'); staffCell.className='whitespace-nowrap px-5 py-3.5 text-sm font-medium text-slate-700'; staffCell.append(icon,document.createTextNode(` ${item.staff}`)); } const badge=pickupElement('span','inline-flex whitespace-nowrap rounded-full px-2.5 py-1 text-xs font-semibold',item.status);badge.classList.add(...(pickupStyles[item.status]??pickupStyles.Cancelled));const action=pickupElement('button','inline-flex min-h-8 cursor-pointer items-center justify-center rounded-lg border border-orange-400 px-3 text-xs font-semibold text-orange-600','View');action.type='button';action.dataset.pickupId=item.id;cells[7].append(badge);cells[8].append(action);tr.append(...cells);return tr; };
    const render = () => { const term=search.value.trim().toLowerCase(); const wanted=pickupTabStatus[activeTab]; const items=data.filter((item)=> (!term||item.order.toLowerCase().includes(term)||item.customer.toLowerCase().includes(term)) && (branch.value==='all'||item.branch===branch.value) && (status.value==='all'||item.status===status.value) && (staff.value==='all'||item.staff===staff.value) && (date.value==='all'||item.date_value===date.value) && (!wanted||item.status===wanted)).sort((a,b)=>sort.value==='oldest'?a.date_value.localeCompare(b.date_value):b.date_value.localeCompare(a.date_value)); const filtered=activeTab!=='all'||term||branch.value!=='all'||status.value!=='all'||staff.value!=='all'||date.value!=='all'; body.replaceChildren(...items.map(row));showing.textContent=items.length?`1–${items.length}`:'0';total.textContent=String(filtered?items.length:(summary.total||items.length));state(items.length?'content':'empty'); };
    const renderBranches = () => { branches.replaceChildren(...branchData.map((item)=>{const tr=pickupElement('tr','border-t border-slate-100');tr.append(pickupElement('td','px-5 py-4 font-semibold text-[#0B1930]',item.branch),pickupElement('td','px-5 py-4 text-sm text-slate-600',`${item.requests} Pickup Requests`),pickupElement('td','px-5 py-4 text-sm text-slate-600',item.breakdown));return tr;}));branchesLoading.classList.add('hidden');branchesContent.classList.remove('hidden'); };
    const load = async () => { state('loading');summaryLoading.classList.remove('hidden');summaryContent.classList.add('hidden');try { const res=await fetch(endpoint,{headers:{Accept:'application/json'}});if(!res.ok)throw new Error();const json=await res.json();if(!json?.summary||!Array.isArray(json.pickup_requests)||!Array.isArray(json.branches))throw new Error();summary=json.summary;data=json.pickup_requests;branchData=json.branches;page.querySelectorAll('[data-admin-pickups-summary]').forEach((el)=>el.textContent=summary[el.dataset.adminPickupsSummary]??0);active.textContent=summary.active_pickups??0;totalLabel.textContent=summary.total??data.length;summaryLoading.classList.add('hidden');summaryContent.classList.remove('hidden');render();renderBranches();}catch(err){state('error');summaryLoading.classList.add('hidden');}};
    tabs.forEach((tab)=>tab.addEventListener('click',()=>{activeTab=tab.dataset.adminPickupsTab;updateTabs();render();}));[branch,status,staff,date,sort].forEach((el)=>el.addEventListener('change',render));search.addEventListener('input',render);clear.addEventListener('click',()=>{activeTab='all';search.value='';branch.value='all';status.value='all';staff.value='all';date.value='all';sort.value='newest';updateTabs();render();});retry.addEventListener('click',load);load();
};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initializeAdminPickups);else initializeAdminPickups();
